create or replace task SALES_DB.RAW.LOAD_SILVER_SALES
	warehouse=COMPUTE_WH
	after SALES_DB.RAW.QUARANTINE_BAD_RECORDS
	as MERGE INTO SALES_DB.SILVER.SALES AS t
    USING (
      SELECT
        SALES_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        STORE_ID,
        TRY_CAST(ORDER_DATE AS DATE) AS ORDER_DATE,
        TRY_CAST(QUANTITY AS NUMBER) AS QUANTITY,
        TRY_CAST(UNIT_PRICE AS FLOAT) AS UNIT_PRICE,
        TRY_CAST(DISCOUNT AS FLOAT) AS DISCOUNT,
        TRY_CAST(TOTAL_AMOUNT AS FLOAT) AS TOTAL_AMOUNT
      FROM SALES_DB.RAW.SALES_STREAM_SILVER
      WHERE CUSTOMER_ID IS NOT NULL
        AND PRODUCT_ID IS NOT NULL
        AND STORE_ID IS NOT NULL
        AND QUANTITY IS NOT NULL
        AND TRY_CAST(QUANTITY AS NUMBER) IS NOT NULL
        AND TRY_CAST(QUANTITY AS NUMBER) > 0
        AND TRY_CAST(DISCOUNT AS FLOAT) IS NOT NULL
    ) AS s
    ON t.SALES_ID = s.SALES_ID
    WHEN NOT MATCHED THEN INSERT (SALES_ID, CUSTOMER_ID, PRODUCT_ID, STORE_ID, ORDER_DATE, QUANTITY, UNIT_PRICE, DISCOUNT, TOTAL_AMOUNT)
    VALUES (s.SALES_ID, s.CUSTOMER_ID, s.PRODUCT_ID, s.STORE_ID, s.ORDER_DATE, s.QUANTITY, s.UNIT_PRICE, s.DISCOUNT, s.TOTAL_AMOUNT);